# Runs software project locally
# You can specify the S3 bucket in docker-compose.env

version: "3.9"

services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - docker-compose.env

  auth:
    build:
      context: .
      dockerfile: backend/src/auth/Dockerfile.dev
    restart: always
    env_file:
      - docker-compose.env
    ports:
      - 6401:6400
    depends_on:
      - database

  marketplace:
    build:
      context: .
      dockerfile: backend/src/marketplace/Dockerfile.dev
    restart: always
    env_file:
      - docker-compose.env
    ports:
      - 6402:6400
    depends_on:
      - database

  notebook:
    build:
      context: .
      dockerfile: backend/src/notebook/Dockerfile.dev
    restart: always
    env_file:
      - docker-compose.env
    ports:
      - 6403:6400
    depends_on:
      - database

  admin:
    build:
      context: .
      dockerfile: backend/src/admin/Dockerfile.dev
    restart: always
    env_file:
      - docker-compose.env
    ports:
      - 6404:6400
    depends_on:
      - database

  reverse-proxy:
    build:
      context: .
      dockerfile: backend/nginx/Dockerfile.dev
    restart: always
    ports:
      - 6400:6400
    depends_on:
      - auth
      - marketplace
      - notebook

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   restart: always
  #   env_file:
  #     - docker-compose.env
  #   ports:
  #     - 3000:80