# Runs software project locally
# You can specify the S3 bucket in docker-compose.env

version: "3.9"

services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - docker-compose.env

  admin:
    build:
      context: .
      dockerfile: backend/src/admin/Dockerfile
    restart: always
    env_file:
      - docker-compose.env
    expose:
      - 6401:6400
    depends_on:
      - database

  auth:
    build:
      context: .
      dockerfile: backend/src/auth/Dockerfile
    restart: always
    env_file:
      - docker-compose.env
    expose:
      - 6402:6400
    depends_on:
      - database

  violations:
    build:
      context: .
      dockerfile: backend/src/violations/Dockerfile
    restart: always
    env_file:
      - docker-compose.env
    expose:
      - 6403:6400
    depends_on:
      - database

  reverse-proxy:
    build:
      context: .
      dockerfile: backend/src/nginx/Dockerfile
    restart: always
    ports:
      - 6400:6400
    depends_on:
      - admin
      - auth
      - violations
