### Install the REST Client extension by Huachao Mao 
### in the VSCode Marketplace to use these endpoints

### Base URL to connect to
@localDns = 127.0.0.1:6400
@serverDns = popo-1349446900.us-east-1.elb.amazonaws.com
@baseUrl = http://{{localDns}}/api/v1

### ------------------------------ USERS ------------------------------
@testToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4ODk1NjA1MiwianRpIjoiMGIzNTQ5MDYtZGM3Yi00YThmLTljZjctMzJiZjVkYmM2ZWRlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImZhMzBhYTBlLWJlMGQtNGVjNi05MTM3LTQ4MzZjZWNlZmM3YSIsIm5iZiI6MTY4ODk1NjA1MiwiZXhwIjoxNjg5MDQyNDUyfQ.MMsYnyxDZYwXp3yxkWGfjUSwpRPM-Z7YHnEwEofMU9k
    "id": "fa30aa0e-be0d-4ec6-9137-4836cecefc7a

### Query the health of the user service.
GET {{baseUrl}}/auth/health

### Signs up a new user.
POST {{baseUrl}}/auth/signup
Content-Type: application/x-www-form-urlencoded

&email=jantoooom@example.org
&username=jantoooom
&password=123

### Logs in a user.
POST {{baseUrl}}/auth/login
Content-Type: application/x-www-form-urlencoded

&username=jantoooom
&password=123

### Logs out a user.
GET {{baseUrl}}/auth/logout
Authorization: {{testToken}}

### ------------------------------ VIOLATIONS ------------------------------
@testViolation = 72c28bee-a6a9-4a4e-872e-a660cdba33e2

### Query the health of the violations service.
GET {{baseUrl}}/violations/health

### List all the violations associated with the session account.
GET {{baseUrl}}/violations
Authorization: {{testToken}}

### Add a new violation associated with the session account.
POST {{baseUrl}}/violation
Authorization: {{testToken}}
Content-Type: application/json

{
    "type": "TWO_SPACES"
}

### ------------------------------ ADMIN ------------------------------

### Query the health of the admin service.
GET {{baseUrl}}/admin/health

### List all the users.
GET {{baseUrl}}/admin/users
Authorization: {{testToken}}

### Delete a violation.
DELETE {{baseUrl}}/admin/{{testViolation}}
Authorization: {{testToken}}
Content-Type: application/json

{
}