### Install the REST Client extension by Huachao Mao 
### in the VSCode Marketplace to use these endpoints

### Base URL to connect to
@localDns = 127.0.0.1:6400
@serverDns = popo-202235509.us-east-1.elb.amazonaws.com
@baseUrl = http://{{localDns}}/api/v1

### ------------------------------ USERS ------------------------------
@testToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4OTI2NjQyNSwianRpIjoiODBhZmNkNGYtODQwYi00OWNjLWFhNTYtZjVjYWI0ZWUwNzExIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjJkMTEwOGUyLTczMTYtNGQ3MC05YjlkLTZkMDk2ZjIyYjk1YyIsIm5iZiI6MTY4OTI2NjQyNSwiZXhwIjoxNjg5MzUyODI1fQ.inTrR2x2Mpl8d6p7E0i4jY4TAMnL9OJuc-Dd3zyTB5I

### Query the health of the user service.
GET {{baseUrl}}/auth/health

### Signs up a new user.
POST {{baseUrl}}/auth/signup
Content-Type: application/x-www-form-urlencoded

&email=jantoooom@example.org
&username=jantoooom
&password=123

### Logs in a user.
POST {{baseUrl}}/auth/login
Content-Type: application/x-www-form-urlencoded

&username=jantoooom
&password=123

### Logs out a user.
GET {{baseUrl}}/auth/logout
Authorization: {{testToken}}

### ------------------------------ VIOLATIONS ------------------------------
@testViolation = 57dde2bf-2607-4f48-bb05-ea248292e702

### Query the health of the violations service.
GET {{baseUrl}}/violations/health

### List all the violations associated with the session account.
GET {{baseUrl}}/violations
Authorization: {{testToken}}

### Add a new violation associated with the session account.
POST {{baseUrl}}/violation
Authorization: {{testToken}}
Content-Type: application/json

{
    "type": "TWO_SPACES"
}

### List one violation associated with the session account.
GET {{baseUrl}}/violations/{{testViolation}}
Authorization: {{testToken}}

### ------------------------------ ADMIN ------------------------------

### Query the health of the admin service.
GET {{baseUrl}}/admin/health

### List all the users.
GET {{baseUrl}}/admin/users
Authorization: {{testToken}}

### Delete a violation.
DELETE {{baseUrl}}/admin/{{testViolation}}
Authorization: {{testToken}}
Content-Type: application/json

{
}

### Reset all tables by dropping and re-creating them.
GET {{baseUrl}}/admin/reset_database
Authorization: {{testToken}}
Content-Type: application/json

{
}